# Docker Compose file for Flask API with MySQL and phpMyAdmin

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: flaskapi
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
      MYSQL_ROOT_PASSWORD: rootpass
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://flaskuser:flaskpass@db:3306/flaskapi
      SECRET_KEY: your-secret-key-here
      JWT_SECRET_KEY: jwt-secret-string
      FLASK_ENV: development
      TELEGRAM_BOT_TOKEN: 8345256867:AAFMasgNavOAstsxPdnOazZfHNRHoNJTbQ0
      TELEGRAM_WEBHOOK_SECRET: supersecret
      ALT_CHANNELS_FILE: alternate_channels.json
      ESCALATE_AFTER_SECONDS: 900
      CLOSE_AFTER_SECONDS: 3600
      FLASK_DEBUG: 1
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "
        echo 'Starting application...' &&
        echo 'Running migrations...' &&
        flask db upgrade &&
        echo 'Starting Gunicorn...' &&
        gunicorn --bind 0.0.0.0:8000 --workers 1 --log-level debug run:app
      "

volumes:
  mysql_data:
