sonar.projectKey=AIP-F25-2_VigilantEye
sonar.organization=AIP-F25-2
sonar.sourceEncoding=UTF-8

# analyze the whole repo
sonar.sources=.

# optional: ignore noise
sonar.exclusions=**/.venv/**,**/__pycache__/**,**/node_modules/**,**/*.ipynb,**/dist/**,**/build/**,**/coverage/**,**/*.log
