"""Add roles and site_id to User model

Revision ID: 9b31b496ba4f
Revises: 96b2b763b3c3
Create Date: 2025-10-07 15:09:47.166844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b31b496ba4f'
down_revision = '96b2b763b3c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('site_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('site_id')
        batch_op.drop_column('roles')

    # ### end Alembic commands ###