"""Initial schema

Revision ID: 37db319c944c
Revises: 
Create Date: 2025-11-10 07:30:53.719335+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37db319c944c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('stream_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'maintenance')", name='ck_cameras_status_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_name'), 'cameras', ['name'], unique=False)
    op.create_index('ix_cameras_status', 'cameras', ['status'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint("role IN ('staff', 'admin')", name='ck_users_role_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_active_not_deleted', 'users', ['is_active', 'is_deleted'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint("status IN ('success', 'failure', 'error')", name='ck_audit_logs_status_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_logs_status', 'audit_logs', ['status'], unique=False)
    op.create_index('ix_audit_logs_user_action', 'audit_logs', ['user_id', 'action'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('access_token', sa.String(length=500), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_index('ix_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('ix_sessions_user_active', 'sessions', ['user_id', 'is_active'], unique=False)
    op.create_table('videos',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=500), nullable=False),
    sa.Column('camera_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('upload_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('filesize', sa.BigInteger(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('analysis_result', sa.String(length=20), nullable=True),
    sa.Column('analysis_completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint("status IN ('uploading', 'processing', 'ready', 'analyzing', 'analyzed', 'error')", name='ck_videos_status_valid'),
    sa.CheckConstraint("upload_type IN ('upload', 'stream')", name='ck_videos_upload_type_valid'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_videos_analysis_result', 'videos', ['analysis_result'], unique=False)
    op.create_index('ix_videos_camera_id', 'videos', ['camera_id'], unique=False)
    op.create_index('ix_videos_created_status', 'videos', ['created_at', 'status'], unique=False)
    op.create_index('ix_videos_expires_at', 'videos', ['expires_at'], unique=False)
    op.create_index('ix_videos_status', 'videos', ['status'], unique=False)
    op.create_index('ix_videos_user_id', 'videos', ['user_id'], unique=False)
    op.create_table('persons',
    sa.Column('video_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('person_tracking_id', sa.String(length=50), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('total_appearances', sa.Integer(), nullable=False),
    sa.Column('age_estimate', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('ethnicity', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('clothing_description', sa.Text(), nullable=True),
    sa.Column('body_features', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_persons_confidence', 'persons', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_persons_expires_at'), 'persons', ['expires_at'], unique=False)
    op.create_index('ix_persons_tracking_id', 'persons', ['person_tracking_id'], unique=False)
    op.create_index('ix_persons_video_first_seen', 'persons', ['video_id', 'first_seen'], unique=False)
    op.create_index('ix_persons_video_id', 'persons', ['video_id'], unique=False)
    op.create_table('tickets',
    sa.Column('video_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('threat_level', sa.String(length=20), nullable=True),
    sa.Column('assigned_to', mysql.CHAR(length=36), nullable=True),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('escalation_count', sa.Integer(), nullable=False),
    sa.Column('escalation_sent_at', sa.DateTime(), nullable=True),
    sa.Column('sla_breach', sa.Boolean(), nullable=False),
    sa.Column('auto_close_at', sa.DateTime(), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high', 'critical')", name='ck_tickets_priority_valid'),
    sa.CheckConstraint("status IN ('open', 'acknowledged', 'in_progress', 'resolved', 'closed')", name='ck_tickets_status_valid'),
    sa.CheckConstraint("threat_level IS NULL OR threat_level IN ('low', 'medium', 'high', 'critical')", name='ck_tickets_threat_level_valid'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tickets_assigned_to', 'tickets', ['assigned_to'], unique=False)
    op.create_index('ix_tickets_auto_close_at', 'tickets', ['auto_close_at'], unique=False)
    op.create_index('ix_tickets_created_at', 'tickets', ['created_at'], unique=False)
    op.create_index('ix_tickets_escalated', 'tickets', ['escalated'], unique=False)
    op.create_index('ix_tickets_priority', 'tickets', ['priority'], unique=False)
    op.create_index('ix_tickets_sla_breach', 'tickets', ['sla_breach'], unique=False)
    op.create_index('ix_tickets_status', 'tickets', ['status'], unique=False)
    op.create_index('ix_tickets_status_priority_created', 'tickets', ['status', 'priority', 'created_at'], unique=False)
    op.create_table('evidence',
    sa.Column('video_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('ticket_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('filepath', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint("type IN ('frame', 'audio', 'video')", name='ck_evidence_type_valid'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_is_flagged', 'evidence', ['is_flagged'], unique=False)
    op.create_index('ix_evidence_ticket_id', 'evidence', ['ticket_id'], unique=False)
    op.create_index('ix_evidence_ticket_timestamp', 'evidence', ['ticket_id', 'timestamp'], unique=False)
    op.create_index('ix_evidence_type', 'evidence', ['type'], unique=False)
    op.create_index('ix_evidence_video_id', 'evidence', ['video_id'], unique=False)
    op.create_table('ticket_history',
    sa.Column('ticket_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_history_ticket_id', 'ticket_history', ['ticket_id'], unique=False)
    op.create_table('ticket_persons',
    sa.Column('ticket_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('person_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'person_id')
    )
    op.create_index('ix_ticket_persons_person_id', 'ticket_persons', ['person_id'], unique=False)
    op.create_index('ix_ticket_persons_ticket_id', 'ticket_persons', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticket_persons_ticket_id', table_name='ticket_persons')
    op.drop_index('ix_ticket_persons_person_id', table_name='ticket_persons')
    op.drop_table('ticket_persons')
    op.drop_index('ix_ticket_history_ticket_id', table_name='ticket_history')
    op.drop_table('ticket_history')
    op.drop_index('ix_evidence_video_id', table_name='evidence')
    op.drop_index('ix_evidence_type', table_name='evidence')
    op.drop_index('ix_evidence_ticket_timestamp', table_name='evidence')
    op.drop_index('ix_evidence_ticket_id', table_name='evidence')
    op.drop_index('ix_evidence_is_flagged', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_tickets_status_priority_created', table_name='tickets')
    op.drop_index('ix_tickets_status', table_name='tickets')
    op.drop_index('ix_tickets_sla_breach', table_name='tickets')
    op.drop_index('ix_tickets_priority', table_name='tickets')
    op.drop_index('ix_tickets_escalated', table_name='tickets')
    op.drop_index('ix_tickets_created_at', table_name='tickets')
    op.drop_index('ix_tickets_auto_close_at', table_name='tickets')
    op.drop_index('ix_tickets_assigned_to', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('ix_persons_video_id', table_name='persons')
    op.drop_index('ix_persons_video_first_seen', table_name='persons')
    op.drop_index('ix_persons_tracking_id', table_name='persons')
    op.drop_index(op.f('ix_persons_expires_at'), table_name='persons')
    op.drop_index('ix_persons_confidence', table_name='persons')
    op.drop_table('persons')
    op.drop_index('ix_videos_user_id', table_name='videos')
    op.drop_index('ix_videos_status', table_name='videos')
    op.drop_index('ix_videos_expires_at', table_name='videos')
    op.drop_index('ix_videos_created_status', table_name='videos')
    op.drop_index('ix_videos_camera_id', table_name='videos')
    op.drop_index('ix_videos_analysis_result', table_name='videos')
    op.drop_table('videos')
    op.drop_index('ix_sessions_user_active', table_name='sessions')
    op.drop_index('ix_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_audit_logs_user_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_status', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_active_not_deleted', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_cameras_status', table_name='cameras')
    op.drop_index(op.f('ix_cameras_name'), table_name='cameras')
    op.drop_table('cameras')
    # ### end Alembic commands ###

