name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    # If you set up a self-hosted runner on your PC, change this to: self-hosted
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install test deps
        run: python -m pip install -U pip pytest pytest-cov

      - name: Run tests (creates reports for Sonar)
        run: |
          mkdir reports
          python -m pytest -q --junitxml=reports/tests.xml --cov=. --cov-report=xml:reports/coverage.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
